services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: on-failure
    ports:
      - 8080:8080
      - 5000:5000
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - jenkins_data:/var/jenkins/home

volumes:
  jenkins_data:
